// Can't reproduce this one. I can get an error similiar to show, but that's
// because it's just the output of cyclicErrors.println with a string error in
// TypeErrors not using this message.
// START
@main def CyclicReferenceInvolvingID = ()
// END
